FROM node:18-alpine AS build

WORKDIR /app
COPY package.json package-lock.json vite.config.ts tsconfig.json ./
COPY .env .env 
RUN npm ci

COPY index.html ./
COPY public ./public
COPY src ./src

RUN npm run build

FROM node:18-alpine AS production
WORKDIR /app
RUN npm install -g serve && apk add --no-cache curl

COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
